### ISSUE TITLE
question regarding the data for conditional generation

### ISSUE THREAD

**Issue by bowen-gao** [Shen-Lab/LDM-3DG#2]
I got this error when trying to unzip the file:

error [AE_geom_cond_weights_and_data.zip]:  start of central directory not found;
  zipfile corrupt.

**Comment by yyou1996** [comment]
Hi,

I am replacing the data files in these several days which should solve the issue soon.

**Comment by bowen-gao** [comment]
Thanks!

**Comment by yyou1996** [comment]
Files are replaced.
